[2025-07-28T21:58:33.359+0000] {processor.py:157} INFO - Started process (PID=4649) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:58:33.359+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T21:58:33.360+0000] {logging_mixin.py:151} INFO - [2025-07-28T21:58:33.360+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:58:33.364+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:58:33.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.020 seconds
[2025-07-28T21:59:03.924+0000] {processor.py:157} INFO - Started process (PID=4679) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:03.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T21:59:03.925+0000] {logging_mixin.py:151} INFO - [2025-07-28T21:59:03.925+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:03.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:03.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.021 seconds
[2025-07-28T21:59:34.330+0000] {processor.py:157} INFO - Started process (PID=4709) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:34.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T21:59:34.332+0000] {logging_mixin.py:151} INFO - [2025-07-28T21:59:34.332+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:34.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T21:59:34.350+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.022 seconds
[2025-07-28T22:00:05.026+0000] {processor.py:157} INFO - Started process (PID=4739) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:05.027+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:00:05.027+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:00:05.027+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:05.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:05.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.031 seconds
[2025-07-28T22:00:31.779+0000] {processor.py:157} INFO - Started process (PID=4769) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:31.780+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:00:31.780+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:00:31.780+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:31.786+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:00:31.783+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:00:31.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:00:31.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.022 seconds
[2025-07-28T22:01:02.131+0000] {processor.py:157} INFO - Started process (PID=4793) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:02.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:01:02.138+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:01:02.138+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:02.147+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:01:02.145+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:01:02.147+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:02.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.056 seconds
[2025-07-28T22:01:32.689+0000] {processor.py:157} INFO - Started process (PID=4823) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:32.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:01:32.693+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:01:32.693+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:32.709+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:01:32.706+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:01:32.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:01:32.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.060 seconds
[2025-07-28T22:02:03.318+0000] {processor.py:157} INFO - Started process (PID=4853) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:03.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:02:03.323+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:02:03.322+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:03.340+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:02:03.339+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:02:03.340+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:03.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.066 seconds
[2025-07-28T22:02:33.947+0000] {processor.py:157} INFO - Started process (PID=4883) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:33.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:02:33.950+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:02:33.950+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:33.960+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:02:33.959+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:02:33.960+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:02:33.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.040 seconds
[2025-07-28T22:03:04.477+0000] {processor.py:157} INFO - Started process (PID=4913) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:04.480+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:03:04.486+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:03:04.485+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:04.507+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:03:04.505+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:03:04.507+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:04.561+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.097 seconds
[2025-07-28T22:03:35.252+0000] {processor.py:157} INFO - Started process (PID=4943) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:35.254+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:03:35.255+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:03:35.255+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:35.267+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:03:35.266+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:03:35.267+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:03:35.296+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.052 seconds
[2025-07-28T22:04:05.939+0000] {processor.py:157} INFO - Started process (PID=4973) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:05.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:04:05.944+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:04:05.943+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:05.951+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:04:05.949+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:04:05.952+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:05.965+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.035 seconds
[2025-07-28T22:04:36.412+0000] {processor.py:157} INFO - Started process (PID=5003) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:36.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:04:36.415+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:04:36.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:36.433+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:04:36.427+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:04:36.435+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:04:36.464+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.065 seconds
[2025-07-28T22:05:07.039+0000] {processor.py:157} INFO - Started process (PID=5033) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:07.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:05:07.043+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:05:07.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:07.059+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:05:07.057+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:05:07.060+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:07.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.079 seconds
[2025-07-28T22:05:37.838+0000] {processor.py:157} INFO - Started process (PID=5063) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:37.846+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:05:37.847+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:05:37.846+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:37.861+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:05:37.858+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:05:37.862+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:05:37.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.076 seconds
[2025-07-28T22:06:08.589+0000] {processor.py:157} INFO - Started process (PID=5093) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:08.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:06:08.595+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:06:08.594+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:08.620+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:06:08.614+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:06:08.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:08.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.081 seconds
[2025-07-28T22:06:39.475+0000] {processor.py:157} INFO - Started process (PID=5123) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:39.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:06:39.483+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:06:39.479+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:39.496+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:06:39.494+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:06:39.496+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:06:39.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.062 seconds
[2025-07-28T22:07:10.017+0000] {processor.py:157} INFO - Started process (PID=5153) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:10.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:07:10.019+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:07:10.019+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:10.029+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:07:10.026+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:07:10.033+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:10.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:07:40.571+0000] {processor.py:157} INFO - Started process (PID=5182) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:40.573+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:07:40.574+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:07:40.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:40.594+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:07:40.589+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:07:40.594+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:07:40.709+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.152 seconds
[2025-07-28T22:08:11.213+0000] {processor.py:157} INFO - Started process (PID=5212) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:11.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:08:11.220+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:08:11.220+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:11.244+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:08:11.237+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:08:11.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:11.299+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.096 seconds
[2025-07-28T22:08:41.568+0000] {processor.py:157} INFO - Started process (PID=5242) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:41.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:08:41.570+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:08:41.570+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:41.578+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:08:41.576+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:08:41.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:08:41.604+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:09:11.891+0000] {processor.py:157} INFO - Started process (PID=5272) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:11.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:09:11.894+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:09:11.894+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:11.902+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:09:11.900+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:09:11.902+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:11.926+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.042 seconds
[2025-07-28T22:09:42.677+0000] {processor.py:157} INFO - Started process (PID=5302) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:42.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:09:42.683+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:09:42.682+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:42.692+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:09:42.688+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:09:42.694+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:09:42.724+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.053 seconds
[2025-07-28T22:10:13.026+0000] {processor.py:157} INFO - Started process (PID=5332) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:13.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:10:13.029+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:10:13.029+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:13.036+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:10:13.034+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:10:13.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:13.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.042 seconds
[2025-07-28T22:10:43.604+0000] {processor.py:157} INFO - Started process (PID=5362) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:43.605+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:10:43.606+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:10:43.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:43.611+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:10:43.610+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:10:43.611+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:10:43.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:11:14.228+0000] {processor.py:157} INFO - Started process (PID=5392) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:14.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:11:14.230+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:11:14.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:14.235+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:11:14.234+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:11:14.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:14.252+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.029 seconds
[2025-07-28T22:11:44.829+0000] {processor.py:157} INFO - Started process (PID=5421) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:44.831+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:11:44.832+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:11:44.831+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:44.841+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:11:44.839+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:11:44.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:11:44.872+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.049 seconds
[2025-07-28T22:12:15.404+0000] {processor.py:157} INFO - Started process (PID=5451) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:15.406+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:12:15.407+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:12:15.407+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:15.416+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:12:15.414+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:12:15.416+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:15.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:12:45.978+0000] {processor.py:157} INFO - Started process (PID=5481) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:45.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:12:45.980+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:12:45.980+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:45.987+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:12:45.985+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:12:45.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:12:46.024+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.055 seconds
[2025-07-28T22:13:16.539+0000] {processor.py:157} INFO - Started process (PID=5511) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:16.540+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:13:16.541+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:13:16.540+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:16.546+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:13:16.545+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:13:16.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:16.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:13:47.001+0000] {processor.py:157} INFO - Started process (PID=5541) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:47.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:13:47.004+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:13:47.003+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:47.011+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:13:47.010+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:13:47.011+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:13:47.036+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.042 seconds
[2025-07-28T22:14:17.669+0000] {processor.py:157} INFO - Started process (PID=5571) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:17.670+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:14:17.671+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:14:17.671+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:17.675+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:14:17.674+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:14:17.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:17.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.022 seconds
[2025-07-28T22:14:48.162+0000] {processor.py:157} INFO - Started process (PID=5601) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:48.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:14:48.163+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:14:48.163+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:48.168+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:14:48.167+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:14:48.168+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:14:48.183+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.025 seconds
[2025-07-28T22:15:18.637+0000] {processor.py:157} INFO - Started process (PID=5631) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:18.639+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:15:18.641+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:15:18.640+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:18.651+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:15:18.647+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:15:18.652+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:18.682+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.061 seconds
[2025-07-28T22:15:49.285+0000] {processor.py:157} INFO - Started process (PID=5661) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:49.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:15:49.287+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:15:49.287+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:49.293+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:15:49.292+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:15:49.293+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:15:49.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.034 seconds
[2025-07-28T22:16:19.975+0000] {processor.py:157} INFO - Started process (PID=5691) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:19.976+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:16:19.977+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:16:19.977+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:19.982+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:16:19.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:16:19.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:19.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.030 seconds
[2025-07-28T22:16:50.296+0000] {processor.py:157} INFO - Started process (PID=5728) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:50.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:16:50.298+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:16:50.298+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:50.302+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:16:50.301+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:16:50.303+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:16:50.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.031 seconds
[2025-07-28T22:17:20.913+0000] {processor.py:157} INFO - Started process (PID=5758) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:20.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:17:20.917+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:17:20.915+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:20.931+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:17:20.929+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:17:20.931+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:20.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.055 seconds
[2025-07-28T22:17:51.616+0000] {processor.py:157} INFO - Started process (PID=5788) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:51.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:17:51.618+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:17:51.618+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:51.624+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:17:51.623+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:17:51.625+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:17:51.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.042 seconds
[2025-07-28T22:18:21.946+0000] {processor.py:157} INFO - Started process (PID=5818) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:21.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:18:21.949+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:18:21.949+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:21.955+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:18:21.954+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:18:21.956+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:21.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.036 seconds
[2025-07-28T22:18:52.412+0000] {processor.py:157} INFO - Started process (PID=5848) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:52.414+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:18:52.415+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:18:52.414+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:52.422+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:18:52.421+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:18:52.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:18:52.448+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:19:23.039+0000] {processor.py:157} INFO - Started process (PID=5878) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:23.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:19:23.042+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:23.041+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:23.051+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:23.049+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 4, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:19:23.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:23.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:19:40.228+0000] {processor.py:157} INFO - Started process (PID=5901) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:40.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:19:40.230+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:40.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:40.236+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:40.235+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:19:40.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:40.253+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.029 seconds
[2025-07-28T22:19:49.316+0000] {processor.py:157} INFO - Started process (PID=5906) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:49.319+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:19:49.320+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:49.320+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:49.327+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:19:49.326+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:19:49.327+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:19:49.353+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:20:19.667+0000] {processor.py:157} INFO - Started process (PID=5936) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:19.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:20:19.670+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:20:19.670+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:19.678+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:20:19.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:20:19.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:19.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.043 seconds
[2025-07-28T22:20:50.231+0000] {processor.py:157} INFO - Started process (PID=5966) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:50.232+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:20:50.233+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:20:50.232+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:50.237+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:20:50.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:20:50.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:20:50.257+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:21:20.913+0000] {processor.py:157} INFO - Started process (PID=5996) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:20.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:21:20.915+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:21:20.915+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:20.920+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:21:20.919+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:21:20.920+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:20.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.031 seconds
[2025-07-28T22:21:51.430+0000] {processor.py:157} INFO - Started process (PID=6033) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:51.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:21:51.432+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:21:51.432+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:51.439+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:21:51.438+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:21:51.439+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:21:51.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.033 seconds
[2025-07-28T22:22:22.254+0000] {processor.py:157} INFO - Started process (PID=6063) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:22.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:22:22.258+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:22.258+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:22.270+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:22.266+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProdueOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:22:22.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:22.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.070 seconds
[2025-07-28T22:22:34.985+0000] {processor.py:157} INFO - Started process (PID=6074) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:34.988+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:22:34.991+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:34.990+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:35.006+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:35.003+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:22:35.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:35.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.076 seconds
[2025-07-28T22:22:43.666+0000] {processor.py:157} INFO - Started process (PID=6091) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:43.667+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:22:43.667+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:43.667+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:43.671+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:43.670+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:22:43.672+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:43.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.024 seconds
[2025-07-28T22:22:51.741+0000] {processor.py:157} INFO - Started process (PID=6103) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:51.743+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:22:51.744+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:51.743+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:51.762+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:22:51.761+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:22:51.763+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:22:51.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.045 seconds
[2025-07-28T22:23:21.320+0000] {processor.py:157} INFO - Started process (PID=6126) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:21.321+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:23:21.322+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:23:21.322+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:21.326+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:23:21.325+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 11
    start_date=start_date,
              ^
SyntaxError: invalid syntax
[2025-07-28T22:23:21.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:21.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.029 seconds
[2025-07-28T22:23:37.847+0000] {processor.py:157} INFO - Started process (PID=6144) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:37.848+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:23:37.848+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:23:37.848+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:37.853+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:23:37.852+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:23:37.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:23:37.869+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:24:08.781+0000] {processor.py:157} INFO - Started process (PID=6174) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:08.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:24:08.783+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:24:08.783+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:08.789+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:24:08.788+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:24:08.789+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:08.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:24:39.277+0000] {processor.py:157} INFO - Started process (PID=6204) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:39.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:24:39.279+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:24:39.279+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:39.286+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:24:39.285+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:24:39.286+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:24:39.307+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.044 seconds
[2025-07-28T22:25:09.772+0000] {processor.py:157} INFO - Started process (PID=6234) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:09.773+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:25:09.774+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:09.774+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:09.781+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:09.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:25:09.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:09.802+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.036 seconds
[2025-07-28T22:25:13.818+0000] {processor.py:157} INFO - Started process (PID=6239) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:13.821+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:25:13.822+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:13.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:13.839+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:13.838+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:25:13.840+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:13.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.039 seconds
[2025-07-28T22:25:44.377+0000] {processor.py:157} INFO - Started process (PID=6269) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:44.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:25:44.379+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:44.379+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:44.388+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:25:44.386+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:25:44.393+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:25:44.406+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.034 seconds
[2025-07-28T22:26:14.941+0000] {processor.py:157} INFO - Started process (PID=6299) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:14.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:26:14.944+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:26:14.943+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:14.952+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:26:14.950+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:26:14.952+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:14.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.033 seconds
[2025-07-28T22:26:45.499+0000] {processor.py:157} INFO - Started process (PID=6329) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:45.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:26:45.502+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:26:45.501+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:45.516+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:26:45.511+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:26:45.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:26:45.537+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.044 seconds
[2025-07-28T22:27:15.996+0000] {processor.py:157} INFO - Started process (PID=6359) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:15.997+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:27:15.998+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:15.998+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:16.006+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:16.003+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:27:16.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:16.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:27:46.513+0000] {processor.py:157} INFO - Started process (PID=6388) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:46.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:27:46.515+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:46.514+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:46.522+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:46.520+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:27:46.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:46.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.037 seconds
[2025-07-28T22:27:59.692+0000] {processor.py:157} INFO - Started process (PID=6412) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:59.694+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:27:59.695+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:59.694+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:59.701+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:27:59.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:27:59.701+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:27:59.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.037 seconds
[2025-07-28T22:28:30.314+0000] {processor.py:157} INFO - Started process (PID=6441) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:30.316+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:28:30.317+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:28:30.316+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:30.324+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:28:30.323+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'kafka_operator'
[2025-07-28T22:28:30.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:30.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:28:34.373+0000] {processor.py:157} INFO - Started process (PID=6446) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:34.374+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:28:34.375+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:28:34.375+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:34.381+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:28:34.380+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:28:34.381+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:28:34.396+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:29:04.680+0000] {processor.py:157} INFO - Started process (PID=6476) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:04.681+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:29:04.682+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:29:04.681+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:04.687+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:29:04.686+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:29:04.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:04.712+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.038 seconds
[2025-07-28T22:29:35.010+0000] {processor.py:157} INFO - Started process (PID=6506) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:35.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:29:35.012+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:29:35.012+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:35.019+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:29:35.018+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:29:35.020+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:29:35.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.035 seconds
[2025-07-28T22:30:05.559+0000] {processor.py:157} INFO - Started process (PID=6536) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:05.561+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:30:05.562+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:30:05.562+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:05.571+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:30:05.569+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:30:05.571+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:05.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.042 seconds
[2025-07-28T22:30:36.053+0000] {processor.py:157} INFO - Started process (PID=6566) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:36.053+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:30:36.054+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:30:36.054+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:36.058+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:30:36.058+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:30:36.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:30:36.073+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.024 seconds
[2025-07-28T22:31:06.594+0000] {processor.py:157} INFO - Started process (PID=6596) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:06.595+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:31:06.596+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:06.596+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:06.602+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:06.601+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:31:06.602+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:06.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:31:37.137+0000] {processor.py:157} INFO - Started process (PID=6626) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:37.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:31:37.142+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:37.141+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:37.149+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:37.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:31:37.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:37.179+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.048 seconds
[2025-07-28T22:31:55.031+0000] {processor.py:157} INFO - Started process (PID=6674) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:55.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:31:55.031+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:55.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:55.034+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:31:55.033+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:31:55.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:31:55.041+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.012 seconds
[2025-07-28T22:32:25.956+0000] {processor.py:157} INFO - Started process (PID=6704) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:25.956+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:32:25.957+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:32:25.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:25.959+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:32:25.958+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:32:25.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:25.966+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.012 seconds
[2025-07-28T22:32:57.248+0000] {processor.py:157} INFO - Started process (PID=6744) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:57.249+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:32:57.249+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:32:57.249+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:57.253+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:32:57.252+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:32:57.253+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:32:57.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.035 seconds
[2025-07-28T22:33:46.421+0000] {processor.py:157} INFO - Started process (PID=196) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:33:46.421+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:33:46.422+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:33:46.421+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:33:46.423+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:33:46.423+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:33:46.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:33:46.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.011 seconds
[2025-07-28T22:34:17.155+0000] {processor.py:157} INFO - Started process (PID=226) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:17.155+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:34:17.155+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:34:17.155+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:17.157+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:34:17.157+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from plugins.kafka_operator import KafkaProduceOperator
ModuleNotFoundError: No module named 'plugins'
[2025-07-28T22:34:17.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:17.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.010 seconds
[2025-07-28T22:34:34.326+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:34.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:34:34.330+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:34:34.328+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:34.336+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:34:34.335+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:34:34.336+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:34:34.358+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.036 seconds
[2025-07-28T22:35:04.907+0000] {processor.py:157} INFO - Started process (PID=261) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:04.908+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:35:04.909+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:35:04.909+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:04.914+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:35:04.913+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:35:04.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:04.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.037 seconds
[2025-07-28T22:35:35.398+0000] {processor.py:157} INFO - Started process (PID=291) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:35.400+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:35:35.400+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:35:35.400+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:35.405+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:35:35.404+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:35:35.405+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:35:35.421+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:36:05.996+0000] {processor.py:157} INFO - Started process (PID=321) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:05.997+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:36:05.998+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:36:05.998+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:06.004+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:36:06.003+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:36:06.004+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:06.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.027 seconds
[2025-07-28T22:36:36.464+0000] {processor.py:157} INFO - Started process (PID=351) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:36.465+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:36:36.465+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:36:36.465+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:36.469+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:36:36.468+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:36:36.469+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:36:36.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.020 seconds
[2025-07-28T22:37:06.901+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:06.902+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:37:06.903+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:37:06.903+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:06.910+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:37:06.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:37:06.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:06.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.032 seconds
[2025-07-28T22:37:37.389+0000] {processor.py:157} INFO - Started process (PID=411) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:37.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:37:37.391+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:37:37.391+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:37.396+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:37:37.395+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:37:37.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:37:37.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.030 seconds
[2025-07-28T22:38:07.822+0000] {processor.py:157} INFO - Started process (PID=441) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:07.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:38:07.824+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:38:07.824+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:07.830+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:38:07.828+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:38:07.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:07.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.029 seconds
[2025-07-28T22:38:38.323+0000] {processor.py:157} INFO - Started process (PID=471) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:38.324+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:38:38.325+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:38:38.325+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:38.330+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:38:38.329+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:38:38.330+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:38:38.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.027 seconds
[2025-07-28T22:39:08.760+0000] {processor.py:157} INFO - Started process (PID=501) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:08.761+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:39:08.762+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:39:08.762+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:08.768+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:39:08.767+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:39:08.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:08.793+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.037 seconds
[2025-07-28T22:39:39.227+0000] {processor.py:157} INFO - Started process (PID=531) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:39.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:39:39.230+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:39:39.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:39.237+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:39:39.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:39:39.238+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:39:39.256+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.034 seconds
[2025-07-28T22:40:09.657+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:09.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:40:09.659+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:40:09.659+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:09.664+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:40:09.663+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:40:09.664+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:09.681+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:40:40.131+0000] {processor.py:157} INFO - Started process (PID=591) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:40.131+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:40:40.132+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:40:40.132+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:40.137+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:40:40.136+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:40:40.137+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:40:40.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.024 seconds
[2025-07-28T22:41:10.676+0000] {processor.py:157} INFO - Started process (PID=621) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:10.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:41:10.679+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:41:10.678+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:10.684+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:41:10.683+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:41:10.684+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:10.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.026 seconds
[2025-07-28T22:41:41.125+0000] {processor.py:157} INFO - Started process (PID=651) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:41.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:41:41.126+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:41:41.126+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:41.130+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:41:41.129+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:41:41.130+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:41:41.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.023 seconds
[2025-07-28T22:42:11.592+0000] {processor.py:157} INFO - Started process (PID=681) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:11.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:42:11.594+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:42:11.594+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:11.601+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:42:11.599+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:42:11.601+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:11.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.037 seconds
[2025-07-28T22:42:42.099+0000] {processor.py:157} INFO - Started process (PID=711) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:42.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:42:42.101+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:42:42.100+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:42.105+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:42:42.104+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:42:42.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:42:42.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.024 seconds
[2025-07-28T22:43:12.565+0000] {processor.py:157} INFO - Started process (PID=741) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:12.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:43:12.567+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:43:12.567+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:12.572+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:43:12.571+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:43:12.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:12.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.027 seconds
[2025-07-28T22:43:43.059+0000] {processor.py:157} INFO - Started process (PID=771) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:43.060+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:43:43.061+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:43:43.060+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:43.065+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:43:43.064+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:43:43.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:43:43.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.026 seconds
[2025-07-28T22:44:13.535+0000] {processor.py:157} INFO - Started process (PID=801) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:13.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:44:13.539+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:44:13.538+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:13.548+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:44:13.546+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:44:13.548+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:13.573+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.048 seconds
[2025-07-28T22:44:43.960+0000] {processor.py:157} INFO - Started process (PID=831) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:43.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:44:43.961+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:44:43.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:43.966+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:44:43.965+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:44:43.966+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:44:43.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.028 seconds
[2025-07-28T22:45:14.461+0000] {processor.py:157} INFO - Started process (PID=861) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:45:14.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:45:14.463+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:45:14.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:45:14.468+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:45:14.467+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/transaction_facts_generator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/transaction_facts_generator.py", line 3, in <module>
    from kafka_operator import KafkaProduceOperator
ImportError: cannot import name 'KafkaProduceOperator' from 'kafka_operator' (/opt/airflow/plugins/kafka_operator.py)
[2025-07-28T22:45:14.468+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:45:14.481+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.025 seconds
[2025-07-28T22:46:06.858+0000] {processor.py:157} INFO - Started process (PID=183) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:06.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:46:06.860+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:06.860+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:06.886+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:07.074+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.074+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-07-28T22:46:07.081+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.081+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-07-28T22:46:07.083+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.083+0000] {manager.py:499} INFO - Created Permission View: %s
[2025-07-28T22:46:07.083+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.083+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:transaction_facts_generator' as access control is unset.
[2025-07-28T22:46:07.083+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.083+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:46:07.088+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.088+0000] {dag.py:2937} INFO - Creating ORM DAG for transaction_facts_generator
[2025-07-28T22:46:07.093+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:07.093+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-03-15T00:00:00+00:00, run_after=2025-03-16T00:00:00+00:00
[2025-07-28T22:46:07.109+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.253 seconds
[2025-07-28T22:46:37.836+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:37.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:46:37.842+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:37.841+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:37.863+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:46:37.896+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:37.896+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:46:37.911+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:46:37.911+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-03-15T00:00:00+00:00, run_after=2025-03-16T00:00:00+00:00
[2025-07-28T22:46:37.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.089 seconds
[2025-07-28T22:47:08.389+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:08.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:47:08.391+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:08.390+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:08.401+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:08.419+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:08.419+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:47:08.429+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:08.429+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-04-12T00:00:00+00:00, run_after=2025-04-13T00:00:00+00:00
[2025-07-28T22:47:08.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.052 seconds
[2025-07-28T22:47:38.966+0000] {processor.py:157} INFO - Started process (PID=630) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:38.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:47:38.970+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:38.970+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:38.982+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:47:38.999+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:38.999+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:47:39.011+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:47:39.011+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-11T00:00:00+00:00, run_after=2025-07-12T00:00:00+00:00
[2025-07-28T22:47:39.019+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.057 seconds
[2025-07-28T22:48:09.436+0000] {processor.py:157} INFO - Started process (PID=711) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:09.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:48:09.439+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:09.439+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:09.455+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:09.475+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:09.474+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:48:09.496+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:09.496+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:48:09.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.076 seconds
[2025-07-28T22:48:39.969+0000] {processor.py:157} INFO - Started process (PID=748) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:39.971+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:48:39.972+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:39.971+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:39.990+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:48:40.021+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:40.021+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:48:40.042+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:48:40.042+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:48:40.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.088 seconds
[2025-07-28T22:49:10.581+0000] {processor.py:157} INFO - Started process (PID=778) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:10.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:49:10.583+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:10.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:10.599+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:10.616+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:10.615+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:49:10.629+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:10.629+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:49:10.637+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.060 seconds
[2025-07-28T22:49:41.106+0000] {processor.py:157} INFO - Started process (PID=808) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:41.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:49:41.110+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:41.110+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:41.136+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:49:41.160+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:41.159+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:49:41.178+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:49:41.178+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:49:41.193+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.093 seconds
[2025-07-28T22:50:11.683+0000] {processor.py:157} INFO - Started process (PID=838) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:11.684+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:50:11.685+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:11.684+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:11.700+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:11.718+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:11.718+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:50:11.729+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:11.729+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:50:11.736+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.058 seconds
[2025-07-28T22:50:42.217+0000] {processor.py:157} INFO - Started process (PID=868) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:42.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:50:42.219+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:42.219+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:42.233+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:50:42.259+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:42.259+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:50:42.281+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:50:42.280+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:50:42.300+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.092 seconds
[2025-07-28T22:51:12.839+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:12.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:51:12.842+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:12.842+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:12.867+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:12.908+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:12.908+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:51:12.935+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:12.935+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:51:12.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.118 seconds
[2025-07-28T22:51:43.427+0000] {processor.py:157} INFO - Started process (PID=928) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:43.428+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:51:43.429+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:43.429+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:43.447+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:51:43.477+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:43.477+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:51:43.493+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:51:43.493+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:51:43.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.083 seconds
[2025-07-28T22:52:14.039+0000] {processor.py:157} INFO - Started process (PID=964) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:14.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:52:14.042+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:14.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:14.054+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:14.079+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:14.079+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:52:14.095+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:14.095+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:52:14.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.073 seconds
[2025-07-28T22:52:44.564+0000] {processor.py:157} INFO - Started process (PID=1004) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:44.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:52:44.565+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:44.564+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:44.571+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:52:44.588+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:44.588+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:52:44.598+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:52:44.598+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:52:44.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.044 seconds
[2025-07-28T22:53:15.125+0000] {processor.py:157} INFO - Started process (PID=1039) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:15.126+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:53:15.127+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:15.126+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:15.147+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:15.170+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:15.170+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:53:15.184+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:15.184+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:53:15.192+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.073 seconds
[2025-07-28T22:53:45.708+0000] {processor.py:157} INFO - Started process (PID=1074) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:45.710+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:53:45.711+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:45.711+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:45.725+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:53:45.751+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:45.751+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:53:45.767+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:53:45.767+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:53:45.776+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.074 seconds
[2025-07-28T22:54:16.247+0000] {processor.py:157} INFO - Started process (PID=1114) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:16.248+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:54:16.249+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:16.248+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:16.259+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:16.283+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:16.283+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:54:16.304+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:16.303+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:54:16.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.072 seconds
[2025-07-28T22:54:46.946+0000] {processor.py:157} INFO - Started process (PID=1156) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:46.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:54:46.949+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:46.948+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:46.961+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:54:46.981+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:46.981+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:54:46.992+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:54:46.992+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:54:46.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.060 seconds
[2025-07-28T22:55:17.565+0000] {processor.py:157} INFO - Started process (PID=1192) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:17.566+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:55:17.567+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:17.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:17.582+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:17.600+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:17.600+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:55:17.613+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:17.613+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:55:17.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.061 seconds
[2025-07-28T22:55:48.166+0000] {processor.py:157} INFO - Started process (PID=1228) to work on /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:48.168+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/transaction_facts_generator.py for tasks to queue
[2025-07-28T22:55:48.170+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:48.170+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:48.187+0000] {processor.py:839} INFO - DAG(s) dict_keys(['transaction_facts_generator']) retrieved from /opt/airflow/dags/transaction_facts_generator.py
[2025-07-28T22:55:48.205+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:48.205+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-07-28T22:55:48.222+0000] {logging_mixin.py:151} INFO - [2025-07-28T22:55:48.222+0000] {dag.py:3696} INFO - Setting next_dagrun for transaction_facts_generator to 2025-07-28T00:00:00+00:00, run_after=2025-07-29T00:00:00+00:00
[2025-07-28T22:55:48.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/transaction_facts_generator.py took 0.067 seconds
